apiVersion: v1
kind: Service
metadata:
  name: solarcalc-frontend-svc
  namespace: solarcalc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: solarcalc-frontend
